docs: improve developer guidebook
ArkEcosystemArchive/docs-legacy pull request #233
Opened 2019-01-10 17:51 UTC by JeremiGendron

## Proposed changes

Refactor the developer guidebook to include more complete instructions on base dependencies and workflow.

Will include more details if necessary or refactor at maintainers' will without problem.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [x] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [x] I have added necessary documentation

2019-01-12 07:58 UTC, kristjank commented
@JeremiGendron we added some bigger content, so we have some conflicts now. When you can resolve them please.

2019-01-12 07:59 UTC, JeremiGendron commented
sure thing

2019-01-15 23:51 UTC, kristjank submitted a review, later dismissed

2019-01-16 17:06 UTC, faustbrian commented
The cookbook was moved to the guidebook.

2019-01-22 09:16 UTC, KaiserKarel commented on docs/cookbook/README.md
> -[open an issue](https://github.com/ArkEcosystem/docs).
change the link to "https://github.com/ArkEcosystem/docs/issues"?

2019-01-22 09:18 UTC, KaiserKarel commented on docs/cookbook/README.md
> +* [Developer](/cookbook/developer/)
this moved to guidebook

2019-01-22 09:25 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +These tools make it easy for us to setup the development environment, everything is handled by scripts provided in the Core's `package.json` file.
set up

2019-01-22 09:36 UTC, KaiserKarel requested changes

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +If you don't have NodeJS and npm installed, the simplest way to manage both is through following instructions on [how to setup nvm for your platform](https://github.com/creationix/nvm).
set up

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +With yarn installed globally, we can proceed to setup the Ark Core repository.
set up :)

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +Finally, we can setup the entire repository with one command:
set up

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +For example, the `.nvmrc` file located at `core/.nvmrc` will tell us which version of node we should use for development.
consider using NodeJS as often as possible, as node might confuse beginners. Do we mean an Ark Node, relay or forging, or programming language?

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +[Yarn](https://yarnpkg.com) is the package manager used by Ark Core, it replaces npm from here on out.
`;` or a new sentence is slightly more appropriate

2019-01-22 09:36 UTC, KaiserKarel commented on docs/guidebook/core/development.md
> +Before sending any PRs or pushing to GitHub please make sure to run `yarn lint` to enforce the rules described in `tslint.json`.
There should definitely be a comma after Github[...](https://www.youtube.com/watch?v=qmVnr7rsWrE)

2019-01-22 11:35 UTC, JeremiGendron commented
Alright will change everything as suggested

On Tue, Jan 22, 2019, 4:36 AM Karel L. Kubat <notifications@github.com
wrote:

> *@KaiserKarel* requested changes on this pull request.
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249698307>:
>
> >
> -Before you can get started with working on Ark Core, you need to setup lerna as previously mentioned.
> +## Getting started
> +
> +Firstly, you should have [git](https://git-scm.com) installed.
> +
> +With git installed, the first step is to clone the repository so we can have access to some important files locally:
> +
> +```git
> +git clone https://github.com/arkecosystem/core
> +cd core
> +```
> +
> +For example, the `.nvmrc` file located at `core/.nvmrc` will tell us which version of node we should use for development.
> +
> +If you don't have NodeJS and npm installed, the simplest way to manage both is through following instructions on [how to setup nvm for your platform](https://github.com/creationix/nvm).
>
> set up
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249700195>:
>
> >  ```
>
> -Just follow those steps, and you are ready to get started. Happy Hacking!
> +[Yarn](https://yarnpkg.com) is the package manager used by Ark Core, it replaces npm from here on out.
> +
> +With yarn installed globally, we can proceed to setup the Ark Core repository.
>
> set up :)
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249700267>:
>
> > -Just follow those steps, and you are ready to get started. Happy Hacking!
> +[Yarn](https://yarnpkg.com) is the package manager used by Ark Core, it replaces npm from here on out.
> +
> +With yarn installed globally, we can proceed to setup the Ark Core repository.
> +
> +Before we install all the JavaScript and TypeScript packages, we need to make sure we are on the develop branch.
> +
> +If the output of `git branch` doesn't show 'develop' as the current branch, but shows 'master' in green (current branch), you need to run the following:
> +
> +```git
> +git fetch https://github.com/arkecosystem/core develop:develop
> +git checkout develop
> +```
> +This will ensure that your local files reflect those of the Core's development branch.
> +
> +Finally, we can setup the entire repository with one command:
>
> set up
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249700715>:
>
> >
> -Before you can get started with working on Ark Core, you need to setup lerna as previously mentioned.
> +## Getting started
> +
> +Firstly, you should have [git](https://git-scm.com) installed.
> +
> +With git installed, the first step is to clone the repository so we can have access to some important files locally:
> +
> +```git
> +git clone https://github.com/arkecosystem/core
> +cd core
> +```
> +
> +For example, the `.nvmrc` file located at `core/.nvmrc` will tell us which version of node we should use for development.
>
> consider using NodeJS as often as possible, as node might confuse
> beginners. Do we mean an Ark Node, relay or forging, or programming
> language?
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249701060>:
>
> >  ```
>
> -Just follow those steps, and you are ready to get started. Happy Hacking!
> +[Yarn](https://yarnpkg.com) is the package manager used by Ark Core, it replaces npm from here on out.
>
> ; or a new sentence is slightly more appropriate
> ------------------------------
>
> In docs/guidebook/core/development.md
> <https://github.com/ArkEcosystem/docs/pull/233#discussion_r249701708>:
>
> >
> -Before sending any PRs or pushing to GitHub, please make sure to run `npm run lint` to apply the rules enforced by [StandardJS](https://standardjs.com).
> +Before sending any PRs or pushing to GitHub please make sure to run `yarn lint` to enforce the rules described in `tslint.json`.
>
> There should definitely be a comma after Github...
> <https://www.youtube.com/watch?v=qmVnr7rsWrE>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArkEcosystem/docs/pull/233#pullrequestreview-194904377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWfqZWGXRxox-_OyQQ78Uak9YuzPtPWlks5vFtuegaJpZM4Z6AYr>
> .
>

2019-01-25 05:31 UTC, faustbrian commented
@JeremiGendron any progress on this or should @KaiserKarel finish it?

2019-01-25 17:57 UTC, JeremiGendron commented on docs/cookbook/README.md
> +* [Developer](/cookbook/developer/)
ok, will change

2019-02-02 16:58 UTC, faustbrian commented
@JeremiGendron conflicts and some links still look wrong

2019-02-07 10:51 UTC, faustbrian approved these changes

2019-02-07 10:51 UTC, merged

2019-02-07 10:52 UTC, faustbrian commented
@KaiserKarel could you take a look if anything in here clashes with changes you made lately and adjust them in an upcoming PR of yours.