docs: fix incorrect guide on genesisBlock.json location
ArkEcosystemArchive/docs-legacy pull request #271
Opened 2019-02-13 15:02 UTC by KaiserKarel

## Proposed changes
I incorrectly described how to migrate the genesisBlock.json file. Fixed that and added descriptions on the other files in the crypto/src/networks/{NETWORK} directory.

2019-02-13 15:17 UTC, faustbrian requested changes

2019-02-13 15:17 UTC, faustbrian commented on docs/releases/v2.1/migrating_1.0_2.1.md
> +We also need to move our initial block definition, the genesisBlock, to the correct location. In previous versions it was stored alongside our other files, however, crypto related files now reside in
`packages/crypto/src/networks/{NETWORK}`

2019-02-14 16:38 UTC, kristjank approved these changes

2019-02-14 16:47 UTC, faustbrian approved these changes

2019-02-15 06:09 UTC, merged