[feat] setup dev env cookbook recipe
ArkEcosystemArchive/docs-legacy pull request #70
Opened 2018-10-24 08:48 UTC by mvega3

## Proposed changes
Adds a cookbook recipe for setting up a dev environment and testnet

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Docs (documentation only changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [x] I have added necessary documentation
<!--

## Further comments

Closes #63

2018-10-24 09:24 UTC, faustbrian requested changes

2018-10-24 09:24 UTC, faustbrian commented on docs/faq/README.md
> +* [Passphrases](/faq/passphrases/)
All of these have to be reverted as you otherwise will end up with a bunch of errors and dead URLs.

```
File for relative link "/faq/voting-delegates/" does not exist.
(Resolved file: /Users/dev/code/docs/docs/faq/voting-delegates/README.md)
```

2018-10-24 18:45 UTC, mvega3 commented on docs/faq/README.md
> +* [Passphrases](/faq/passphrases/)
Weird. I dunno why that works in some cases and not in others. Reverted

2018-10-25 02:17 UTC, faustbrian approved these changes

2018-10-25 02:17 UTC, merged