modify identities section to reflect core changes
ArkEcosystemArchive/docs-legacy pull request #84
Opened 2018-10-28 03:19 UTC by JeremiGendron

## Proposed changes

Update examples with `const { identities } = require('@arkecosystem/crypto)`

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [x] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] I have read the [WRITING DOCUMENTATION](https://docs.ark.io/guidebook/contribution-guidelines/writing-documentation.html) guidelines
- [x] I have added necessary documentation

2018-10-28 17:08 UTC, faustbrian requested changes
The examples should use the same addresses, public keys, private keys, WIFs and passphrases as here https://github.com/ArkEcosystem/docs/blame/master/docs/api/sdk/cryptography/php.md#L80.

2018-10-28 17:10 UTC, JeremiGendron commented
@faustbrian ok, changing now

2018-10-28 17:17 UTC, faustbrian requested changes

2018-10-28 17:17 UTC, faustbrian commented on docs/api/sdk/cryptography/javascript.md
> +identities.address.fromPublicKey(keys.privateKey)
This should use the public key from the linked examples.

2018-10-28 17:39 UTC, JeremiGendron commented
@faustbrian have changed, should be OK now

2018-10-29 09:08 UTC, faustbrian approved these changes

2018-10-29 09:10 UTC, merged